image: node:11

stages:
  - prepare
  - test
  - deploy
  - publish
 
variables:
  AWS_DEFAULT_REGION: eu-west-1 
  BUCKET_NAME: blockchain-definitions/v4


cache:
  paths:
    - node_modules/
    - contracts.json 

Prepare:
  stage: prepare
  before_script:
    - apt-get update && apt-get install libudev-dev libusb-1.0-0-dev -y
  script:
    - npm i
  artifacts:
    paths: 
      - node_modules/
  only:
    - integration

Test:
  stage: test
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y netcat && apt-get clean && rm -rf /var/lib/apt/lists/*
  artifacts:
    paths: 
      - coverage/
  script:
    - npm run compile && npm test && npm run solhint && SOLIDITY_COVERAGE=true bash scripts/test.sh
  only:
    - integration
    - master

Deploy:
  stage: deploy
  script:
    - npm run migration:kovan && npm run migration:goerli
  artifacts:
    paths: 
      - contracts.json
      - build/
  only:
    - integration
      
PublishContracts:
  image: "python:latest"  
  stage: publish
  artifacts:
    paths: 
      - contracts.json
  before_script:
    - pip install awscli  
  script:
    - aws s3 cp contracts.json s3://${BUCKET_NAME}/contracts.json
  only:
    - integration

PublishArtifacts:
  image: "python:latest"  
  stage: publish
  artifacts:
    paths: 
      - build/
  before_script:
    - pip install awscli  
  script:
    -  aws s3 cp build/contracts/* s3://${BUCKET_NAME}/artifacts/
  only:
    - integration

PublishCoverage:
  image: "python:latest"  
  stage: publish
  artifacts:
    paths: 
      - coverage/
  before_script:
    - pip install awscli  
  script:
    - aws s3 cp -r coverage s3://${BUCKET_NAME}/
  only:
    - integration
